name: Comment for Merge Dependabot PRs Automatically

on:
  pull_request:
    branches:
      - "dependabot/**"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment to merge dependabot PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
